import assert from 'node:assert/strict';
import {Controls,chooseAutoAimTarget} from '../src/input.js';
const player={x:0,y:0,angle:0},enemy=(angle,distance=200)=>({x:Math.cos(angle)*distance,y:Math.sin(angle)*distance,hp:65,dead:false});
const near=enemy(Math.PI/30),behind=enemy(Math.PI),outside=enemy(Math.PI/8),far=enemy(0,600);
assert.equal(chooseAutoAimTarget(player,[behind,outside,far],null,()=>true,0),null);
assert.equal(chooseAutoAimTarget(player,[near],null,()=>false,0),null);
assert.equal(chooseAutoAimTarget(player,[near],null,()=>true,0),near);
const nearer=enemy(.01,100);assert.equal(chooseAutoAimTarget(player,[near,nearer],near,()=>true,0),near);
near.dead=true;assert.equal(chooseAutoAimTarget(player,[near,nearer],near,()=>true,0),nearer);near.dead=false;
const g={player,state:'playing',keys:{},mouse:{down:false}},noop=()=>{};
const controls=new Controls(g,{unlock:noop,pause:noop,reload:noop,disconnect:noop,menu:noop,confirm:noop,back:noop});
controls.source='pad';controls.autoTarget=near;controls.heading=0;
assert.ok(Math.abs(controls.sample().aimAngle-Math.PI/120)<1e-8);
for(let i=0;i<100;i++)player.angle=controls.sample().aimAngle;
assert.ok(Math.abs(player.angle-Math.PI/120)<1e-8,'assist must not accumulate into target lock');
controls.autoTarget=enemy(.2);assert.ok(Math.abs(controls.sample().aimAngle)<=Math.PI/60);
controls.manualAim=true;assert.equal(controls.sample().aimAngle,0);
const pad={index:0,mapping:'standard',connected:true,axes:[1,0,0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};
controls.poll(1/60,[pad]);assert.ok(Math.abs(controls.heading+Math.PI/4)<1e-8,'left stick alone sets facing');
pad.axes=[0,0,0,0];controls.poll(1/60,[pad]);assert.ok(Math.abs(controls.heading+Math.PI/4)<1e-8,'releasing stick keeps facing');
controls.reset();assert.equal(controls.autoTarget,null);
console.log('PASS single-stick facing, 12-degree cone, blocked/range exclusions, stable targets, 25% correction, 3-degree cap, no accumulating lock and manual override');
